language: node_js
node_js: 
  - 7
before_script:
  - npm install
script:
  - npm run test
after-success:
  - ./node_modules/.bin/jscoverage lib lib-cov
  - ./node_modules/.bin/mocha test/**.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js